using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Code.Core.ServiceLocator.Editor
{
    public static class InstallerGenerator
    {
        [MenuItem("Tools/Sync All Installers")]
        public static void SyncAll()
        {
            string[] asmdefGuids = AssetDatabase.FindAssets("t:asmdef");
            int totalAdded = 0;

            foreach (string guid in asmdefGuids)
            {
                string asmdefPath = AssetDatabase.GUIDToAssetPath(guid);
                string dir = Path.GetDirectoryName(asmdefPath);
                string assemblyName = Path.GetFileNameWithoutExtension(asmdefPath);

                if (assemblyName.Contains("Editor")) continue;

                Assembly assembly;
                try
                {
                    assembly = Assembly.Load(assemblyName);
                }
                catch
                {
                    continue;
                }

                HashSet<string> allTypes = TypeCache.GetTypesDerivedFrom<IService>()
                    .Where(t =>
                        !t.IsInterface &&
                        !t.IsAbstract &&
                        !t.IsGenericTypeDefinition &&
                        !typeof(MonoBehaviour).IsAssignableFrom(t) &&
                        !IsEditorType(t) &&
                        t.Assembly == assembly)
                    .Select(t => GetFullTypeName(t))
                    .ToHashSet();

                if (!allTypes.Any()) continue;

                string outputPath = Path.Combine(dir, "Installer.Generated.cs");

                // Читаем существующие типы сохраняя порядок
                List<string> existingTypes = File.Exists(outputPath)
                    ? ParseExistingTypes(outputPath)
                    : new List<string>();

                // Только новые
                List<string> newTypes = allTypes
                    .Except(existingTypes)
                    .OrderBy(t => t)
                    .ToList();

                if (newTypes.Count == 0)
                {
                    Debug.Log($"[{assemblyName}] No new types.");
                    continue;
                }

                // Старый порядок сохраняется, новые добавляются в конец
                List<string> mergedTypes = existingTypes.Concat(newTypes).ToList();
                WriteGeneratedFile(outputPath, assemblyName, mergedTypes);

                totalAdded += newTypes.Count;
                Debug.Log($"[{assemblyName}] Added {newTypes.Count} types: {string.Join(", ", newTypes)}");
            }

            if (totalAdded > 0)
                AssetDatabase.Refresh();

            Debug.Log($"Sync complete. Total added: {totalAdded}");
        }

        private static List<string> ParseExistingTypes(string path)
        {
            List<string> result = new List<string>();

            foreach (string line in File.ReadAllLines(path))
            {
                string trimmed = line.Trim();
                if (trimmed.StartsWith("typeof(") && trimmed.EndsWith("),"))
                {
                    string typeName = trimmed["typeof(".Length..^2];
                    result.Add(typeName);
                }
            }

            return result;
        }

        private static void WriteGeneratedFile(string path, string assemblyName, List<string> typeNames)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Code.Core.ServiceLocator;");
            sb.AppendLine();
            sb.AppendLine($"namespace {assemblyName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {assemblyName}Installer : IAssemblyInstaller");
            sb.AppendLine("    {");
            sb.AppendLine("        public int Order { get; }");
            sb.AppendLine("        public Type[] GetServiceOrder() => new[]");
            sb.AppendLine("        {");

            foreach (string typeName in typeNames)
                sb.AppendLine($"            typeof({typeName}),");

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString());
        }

        private static bool IsEditorType(Type t)
        {
            // Проверяем, что сборка не из Editor-папки
            string assemblyName = t.Assembly.GetName().Name;
            return assemblyName != null && (
                assemblyName.Contains("Editor") ||
                t.Namespace != null && t.Namespace.Contains(".Editor")
            );
        }

        private static string GetFullTypeName(Type type)
        {
            if (type.IsGenericType)
            {
                // На случай если вдруг появятся generic-реализации
                string genericDef = type.GetGenericTypeDefinition().FullName!;
                int backtickIndex = genericDef.IndexOf('`');
                string baseName = genericDef[..backtickIndex].Replace('+', '.');
                string args = string.Join(", ", type.GetGenericArguments().Select(GetFullTypeName));
                return $"{baseName}<{args}>";
            }

            return type.FullName!.Replace('+', '.'); // вложенные классы
        }
    }
}