// <auto-generated/>
using System;
using Code.Core.ServiceLocator;

namespace Game
{
    public partial class GameInstaller : IAssemblyInstaller
    {
        public int Order { get; } = 1;

        public Type[] GetServiceOrder() => new[]
        {
            typeof(Code.Game.Radio.RadioRepository),
            typeof(Code.Game.Radio.RadioFavoriteContent),
            typeof(Code.Game.Radio.RadioTranslation),
            typeof(Code.Game.Radio.RadioModel),
            typeof(Code.Game.Timers.TimersService),
        };
    }
}
