// <auto-generated/>
using System;
using Code.Core.ServiceLocator;

namespace Core
{
    public partial class CoreInstaller : IAssemblyInstaller
    {
        public int Order { get; }

        public Type[] GetServiceOrder() => new[]
        {
            typeof(Code.Core.Save.SaveLoadService),
        };
    }
}
